# version: '3.3'
# services:
#   nginx:
#     container_name: nginx
#     build:
#       context: ./nginx
#     ports:
#       - 433:433
#     volumes:
#       - ./volume/wordpress:/var/www/wordpress
#     depends_on:
#       - wordpress
#     env_file:
#       - .env
#   wordpress:
#     container_name: wordpress
#     build:
#       context: ./wordpress
#     volumes:
#       - ./volume/wordpress:/var/www/wordpress
#     depends_on:
#       - mariadb
#     env_file:
#       - .env
#   mariadb:
#     container_name: mariadb
#     build:
#       context: ./mariadb
#     env_file:
#       - .env
#     volumes:
#       - ./volume/mariadb:/var/lib/mysql

# # volumes:










version: "3.3"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - 443:443

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    # volumes:
      # - mariadb:/var/lib/mysql
networks:
  inception:;
    driver: bridge
    name: inception

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: ./volume/wordpress

  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: ./volume/mariadb
