version: '3.3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 433:433
    volumes:
      - ./volume/wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
    volumes:
      - ./volume/wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
    env_file:
      - .env
    volumes:
      - ./volume/mariadb:/var/lib/mysql

# volumes:
