version: '3'

services:
  db:
    container_name: mariadb
    build: ./mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_wordpress_database
      MYSQL_USER: your_wordpress_user
      MYSQL_PASSWORD: your_wordpress_user_password
    volumes:
      - ./mariadb_data:/var/lib/mysql
  # wordpress:
  #   image: wordpress
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_NAME: your_wordpress_database
  #     WORDPRESS_DB_USER: your_wordpress_user
  #     WORDPRESS_DB_PASSWORD: your_wordpress_user_password
